### ISSUE TITLE
Can't create new VHD on non-ReFS file systems

### ISSUE THREAD

**Issue by alnicol** [medo64/VhdAttach#1]
The 'RemoveIntegrityStream' method throws an InvalidOperationException when creating a VHD on a non-ReFS file system. The error message states 'Incorrect Function' which I think means the function isn't supported.

**Comment by medo64** [comment]
Can you please send the crash report directly from application?
I will take a look at it in meantime.

**Comment by alnicol** [comment]
There is no crash. After creating a new VHD, I get an error saying unable
to open the vhd file. The file is created on disk, but 0 bytes.

[image: Inline image 1]

Thanks for looking at it.

**Comment by medo64** [comment]
Fixed in commit 8c737f6.
Please check the latest release.

**Comment by alnicol** [comment]
Yup, that release fixes the problem for me. Thanks very much ... and really useful utility.
