### ISSUE TITLE
disable online (update ?) check

### ISSUE THREAD

**Issue by real-easy** [medo64/VhdAttach#10]
where we can disable the internet connection after start ?

5 sec after start the app will connect to:  
Remote Name:  www.medo64.com

where we can disable this ?

**Comment by medo64** [comment]
That's the check for new version.
I don't plan to change it or make it configurable.

**Comment by medo64** [comment]
PS: If it really bothers you, source is available and you can recompile a version without it.

**Comment by real-easy** [comment]
its an windows thing, if i block in firewall, the system hing up a while, this lets look your app buggy and slow.
